allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - sharp
  - workerd
  - es5-ext@0.10.64

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
