name = "log-viewer"
compatibility_date = "2025-09-03"
upload_source_maps = true
main = "./dist/worker/index.js"

[env.production]
compatibility_date = "2025-09-03"

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
